'''
    SLAP module for BeastBot
'''

import ConfigParser
import ircFunc
import mainFunc
import errorhandling
from random import randint

#=======================================================
slaps = ['throws a keyboard at {0}',
'beautifies {0} with some knuckle duster imprints',
'sends hordes of lemmings over {0}',
'slaps {0} around with a pink Macintosh',
'slaps {0} around with nuclear waste',
'throws a playstation at {0}',
'niest in das Gesicht von {0}',
'slaps {0} around a bit with a small Imperial-Class Stardestroyer',
'slaps {0} about with a large Fluffy Donkey.',
'slaps {0} about with a damp womble',
'punches {0} in da ribs',
'grabs {0}\'s hair and rips it out by the roots',
'drives {0} across the head with a bus',
'kicks {0} where the sun don\'t shine',
'shoves a large pencil up {0}\'s nose.',
'slaps {0} around a bit with a large lightbulb.',
'grabs {0}\'s large buttocks and rips them off with his bare hands.',
'slaps {0} across the face with a large bald rabbit',
'slaps {0} up a bit',
'grabs {0} by his feet and chucks him out of the window',
'slaps {0} about a lot with a large snotty hankie',
'slaps {0} about with a golf club',
'slaps {0} about with a dead mole',
'slaps {0} in the face with a damp crustacean',
'slaps {0} about with {0} with {0} with {0} with {0} witttttttthhhhhhh........',
'slaps {0} in the face',
'shooves a large goat up {0}\'s ass',
'throws himself at {0}',
'grabs {0} and sits on him then slowly lets out his noxious gases',
'relieves himself over {0}',
'blasts {0} apart with his womble launcher',
'smacks {0} in her face',
'slaps {0} across the head with a hairy toothbrush',
'slaps {0} about with a squashed frog',
'whacks {0} in the face with a hedgehog',
'grabs {0}\'s legs and breaks them',
'slaps {0} about with a squashed frog',
'chucks a cream cake at {0}',
'rides a rhino into {0}',
'grabs the aluminum bat from the house and runs out to practice baseball with {0}\'s head...whoops!...WHACK!!.. Now {0}\'s pea-sized brain is all over the field! RETARDO!',
'shoves {0} off the nearest cliff',
'smashes a wine bottle over {0}\'s head',
'slaps {0} with a lil sweet kitten --- ahhh 8D',
'grabs his chainsaw off his shelf, steps up to {0} and slowly, so slowly, cuts off his thick neck, letting the blood spew from his arteries, covering $me in the warm liquid',
'picks up his watermellon and smashes it over {0}\'s head',
'plays tiddlewinks with {0}\'s teeth',
'rips out {0}\'s eyeballs and eats them --- mmmmmmm',
'grabs his ice hockey stick and deftly slices off {0}\'s legs',
'pushes {0} into a large food blender',
'shoves a hamster into {0}\'s mouth and slams his jaws together !',
'rides a monster truck over {0}',
'wedgies {0} !!!!! OUCH !!!',
'locks {0} in a freezer and swallows the key :)',
'thoughs a fake left punch at {0} , while at the same time, pulling out his samari sword and, swinging it through the air, slices off {0}\'s ears',
'drops an elephant onto {0}',
'chucks {0} into a pit full of crocodiles',
'rips open {0}\'s gut and pulls out his intestines',
'is ignoring {0}',
'farts in {0}\'s face',
'pours man eating antz over {0}',
'picks {0} up and chucks him in a bath of boiling hot oil',
'gives {0} a lobotomy',
'slices {0}\'s scalp off and starts chewing on his brain',
'slaps {0} about a bit with a small tadpole',
'slaps {0} around with a large whale',
'throws {0} into a volcano',
'blasts {0} apart with his Enhanced Shock Rifle',
'blows {0} apart with his "phat" cow launcher',
'chucks cowpats at {0}',
'showers {0} with sparkling jellyfish',
'blows {0} away with his bad breath',
'takes one look at {0} and is sick all over the floor',
'slaps {0} about a bit with a mouldy sandwich',
'throws a box of feathers at {0}',
'slaps {0} about with his knuckle dusters',
'whacks {0} in the face with an anaconda',
'shoves {0} up a tree',
'gives {0} a box of chocolates',
'cuts {0} into little pieces, puts his bits in envelopes and posts them to antartica',
'grabs {0} and shooves him in a wheely bin',
'grabs {0}\'s head and rips it off. Then with all his will power, summons the belch monster within, and spews his dinner down {0}\'s neck',
'slaps {0} with a reeally FAT CAT - meeeoooowwwww !!!',
'purrs at {0} ;)',
'chucks a concrete cricket ball at {0}\'s head',
'hurls a hurlbat at {0}',
'laughs at the way {0} snorts when he laughs',
'slaps {0} silly with a snotty tissue',
'blows {0} apart with his marble launcher',
'kicks {0} in the balls --- ooo thats GOTTA HURT !!!',
'gives {0} a lump of C4',
'fires 50 pence pieces at {0}',
'fires {0} at the Sun',
'gives {0} a lift to pyscholand',
'locks {0} in a mental institute',
'runs away from {0}\'s hairy arse',
'hits {0} on the head with a large toilet',
'slaps {0} silly with a urinal',
'slaps {0} about a bit with some baguettes',
'uses {0} s a wicket',
'sues {0} for being so ugly',
'waxes {0}\'s legs',
'waxes {0}\'s groin',
'chucks several obese Americans on {0}',
'SCREAMS LOUDLY AT {0}',
'humps {0}',
'slaps {0} about a lot with his little pink handbag',
'Laughs Out Loud at {0}\'s orange and pink hair',
'slaps {0} about a bit with a lump of mercury',
'grinds down {0}\'s fingers down to stubs with a meat grinder',
'covers {0} in sheep skin and sets his wolf after him',
'pushes {0} infront of a thousand stampeding buffalo',
'lobs a hand grenade at {0} and ducks',
'cuts {0} up and feeds him to a penguin',
'puts some screws through {0}\'s eyeballs',
'sniggers at {0}',
'chuckles at {0}\'s fat ass',
'gives {0} a hate bite',
'pulls out {0}\'s teeth with a knife and fork',
'eats {0}\'s ears for dinner',
'plays football with {0}\'s large head',
'breaks both of {0}\'s kneecaps, then puts a box of chocolates out of his reach :)',
'throws {0} into Hell - "Naughty Girl !"',
'gives {0} a @3-->---',
'breaks {0} in half',
'rips out {0}\'s heart',
'glares evilly at {0}',
'punches {0} so hard it punctures his chest and goes through the other side !!',
'pokes {0} up the nose with a pair of chopsticks !!',
'n00bifies {0}',
'slaps {0} about with a fat Leprechaun',
'drowns {0} in a cup of water!',
'slaps {0} about with a giant boob!',
'telefrags {0}',
'throws a bookcase at {0}',
'slaps {0} in the face with a large tree',
'brands "n00b" on {0}\'s forehead',
'kicks {0} in the face',
'flicks ear wax at {0}',
'sticks {0}\'s fingers in a plug socket',
'tips puts {0}\'s feet in cement and throws him into the sea',
'laughs at {0}\'s high heels',
'flicks cds at {0} and accidently slices off {0}\'s fingers',
'bites off {0}\'s ear',
'slices {0}\'s throat with a woodpecker',
'chucks aftershave in {0}\'s eyes',
'shaves off {0}\'s eyebrows while {0} is asleep',
'whups {0}\'s ass at UT',
'blows up {0}\'s pet dog',
'sets a rabid dog upon {0}',
'sends {0}\'s photo to the police as a "Wanted" person',
'chucks {0} in a bath of scorpions',
'laughs like a cheap whore... and starts to ponder his sexuality !!',
'smiles at {0} .. thinking - bet your glad i\'m not feeling trigger happy today {0} :)',
'slaps {0} around a bit with a small trout',
'feeds {0} to the sharks',
'throws {0} off a bridge',
'grabs {0}, ties him down, and waxes his ARSE !!! OUCH !!!',
'puts a plastic bag over {0}\'s head and smiles wickedly as {0} gasps for air',
'slaps {0} about with his monitor',
'tapes {0} to a skateboard and pushes him down a hill towards an oncoming bus',
'flushes {0} down a toilet',
'grabs {0}\'s hands and slaps them down on a red hot cooker',
'pushes {0} into a microwave and hits the cook button !',
'stuffs his face full of chocolate',
'shoves a hairdrier up {0}\'s nose and turns it up to "nose melter" setting',
'chases after {0} with a weed whacker....hey you need a haircut!',
'kicks {0} off his feet onto his knees; KNEEL BEFORE YOUR MASTER !!',
'gets out his brand new bat and knocks {0} around a lot',
'pulls out his bubble gum, chews on it a bit, ponders over the meaning of {0}, then walks away.........',
'slaps {0} with a lil fishy wishy',
'steals {0}\'s cookies. muhahahahaha!',
'falls off his chair from laughter and spills coffee all over the fookin keyboard !!',
'slaps {0} about with a large lampost',
'grabs a handful of cockroaches and shoves them down {0}\'s pants',
'pushes {0} into a bath full of maggots',
'slaps {0} about with an old smelly sock',
'slaps {0} about with a toupee',
'chucks {0} into a large cement mixer with a camel',
'slaps {0} about with his pet camel',
'slaps {0} about a bit with an orchestra',
'opens {0}\'s gob and chucks a hand grenade down his throat and ducks',
'slaps {0} about with windows XP',
'slaps {0} about with windows 98',
'slaps {0} about with windows 95',
'slaps {0} about with linux',
'breaks {0}\'s elbow',
'slaps {0} about with a fat gay telletubbie',
'pokes {0} in the belly button',
'slaps {0} about a lot with a fat mongoose',
'strips {0} naked and then throws pins at him',
'slaps {0} about some with a skinny mongoose',
'pulls out {0}\'s armpit hair !!',
'blasts {0} apart with a fat spud gun !!!',
'throws {0} into a pit of fat belly dancers',
'breaks {0}\'s nose with a green spondge lampost',
'kicks his fat rabbit at {0}',
'rips out his hair in his frustration at {0} !!',
'puts {0} in an oven',
'pulls out {0}\'s lungs through his throat !',
'wonders why {0} has such a fat arse',
'slaps {0} about with a trout, yes thats right, a fucking TROUT !! u got a fucking problem with my trout ? hey ? WELL !! HAVE U !!! TOUGH !!!!!!!!!!!!!!',
'feeds {0} to a hungry pack of dolphins',
'suffocates {0} with a large condom',
'blasts {0} apart with his mobile phone radiation emitter',
'throws {0} infront of an oncoming train',
'gives {0} skydiving lessons without a parachute',
'locks {0} in a suntaning bed',
'cuts open {0}\'s chest then pours salt all over it',
'feeds {0} to the ants',
'drowns {0} in his own vomit',
'slaps {0} silly with an abominable snowman',
'slaps {0} about a bit with a fat elephant',
'chucks pins at {0}',
'gives {0} acupuncture with some large tent pegs',
'gives {0} a whole lot of new orafices by practising his knife throwing skills with {0}',
'drops a ton of bricks on {0}\'s head',
'puts {0} into a Spanish bull ring',
'pulls out {0}\'s tongue ring violently',
'engraves his name on {0}\'s eyeballs',
'slaps {0} about a bit with an old granny',
'slaps {0} about a lot with 2 small eskimos',
'slaps {0} silly with the Titanic',
'gets down on one knee and asks: "Will you marry me {0}?"',
'hands {0} some spikey dildos',
'assaults {0} with a pepper',
'assaults {0} with a dildo',
'assaults {0} with a cabbage',
'assaults {0} with a whistle',
'puts {0} in a jar full of bees',
'performs the round-house kick to {0}\'s face']
#=======================================================

def init():
    modulename = "slap"
    config = ConfigParser.ConfigParser()
    config.read('conf/beastbot.conf')
    config.set('Modules', 'slap', 'loaded')
    config.set('Functions', 'slap', 'slap.slap')

    with open('conf/beastbot.conf', 'wb') as configfile:
        config.write(configfile)

init()

def slap(line, irc):
    conf = mainFunc.getConfig()
    splitline = line.split(" :")
    message, whole, username, msgto = ircFunc.ircMessage(line, whl=True)
    try:
        if (len(message) > 1):
            output = ""
            if (message[1] == conf['nick']):
                output = slaps[randint(0, len(slaps)-1)].format("itself")
            else:
                output = slaps[randint(0, len(slaps)-1)].format(whole)
            ircFunc.ircSay(msgto, output, irc)
    except Exception, e:
        errorhandling.errorlog('critical', e, line)